### ISSUE TITLE
Add support for Athena

### ISSUE THREAD

**Issue by johanjvrens** [datafold/data-diff#154]
Hi, 
Is [Athena](https://aws.amazon.com/athena/) in the pipeline to be added as a Supported Databases?

Regards Johan

**Comment by erezsh** [comment]
Hi @johanjvrens ,

Athena is currently not considered a high priority, but we might implement it if the demand is high  (please vote 👍🏼 for feature requests).

However, contributions are very welcome! If you'd like to try, we'll be happy to help you in the process.

**Comment by niger-prequel** [comment]
Would love to know more about how to get this going, [we're](prequel.co) possibly open to taking it on

**Comment by erezsh** [comment]
Hi @niger-prequel , that's great to hear.

To get started, read these:

1. https://github.com/datafold/data-diff/blob/master/CONTRIBUTING.md

2. https://data-diff.readthedocs.io/en/latest/new-database-driver-guide.html

Also, ideally you would add Athena to `docker-compose.yml`, so that  `docker-compose up athena` would set it up to pass the tests.

If you have any questions, or need advice, feel free to ask!

**Comment by osalloum** [comment]
+1

**Comment by dwp0980** [comment]
+1
