### ISSUE TITLE
Add support for DB2

### ISSUE THREAD

**Issue by clober** [datafold/data-diff#159]
Hi, do you have a plan in your roadmap to add support for DB2 databases?

Thanks, Carlos.

**Comment by nolar** [comment]
Hello. Thanks for asking.

The DB2 per see is not on the roadmap. But stabilizing the database connection protocol and making it extensible is one of the highest priorities — so that you could write your own driver for DB2.

As of now, you can do this by forking the repo and implementing the connector in your fork, and updating it from time to time (but the protocol might slightly change in the future — as it is typical with [zerover](https://0ver.org/)-stage projects).

**Comment by FrankBergemann** [comment]
I would also appreciate support for DB2 databases.
