### ISSUE TITLE
Make all format options available when using `--dbt`

### ISSUE THREAD

**Issue by dbeatty10** [datafold/data-diff#409]
**Is your feature request related to a problem? Please describe.**
Currently, the `--dbt` flag uses a different output format than non- `--dbt` executions of `data-diff`.

**Describe the solution you'd like**
Ideally, regular `data-diff` and `data-diff --dbt` would have the same output format. Additionally, `--json` and `--stats` should be possible when using `--dbt`.

**Describe alternatives you've considered**
It's an option for `--dbt` to have completely different formatting and for the `--json` and `--stats` flags to not have any effect. But that alternative makes dolphins cry 🐬 😢 

**Additional context**
I'll submit a PR!

**Comment by dlawin** [comment]
> Ideally, regular data-diff and data-diff --dbt would have the same output format

I'm not sure I agree as we are targeting two very **_diff_** erent uses cases in these two features, so I do think it makes sense for the output to not align **_by default_**

Migrations (primary data-diff use case) vs. dbt model development. But 100% we need parity across features around the output options (not to mention the other diff options flags)

> It's an option for --dbt to have completely different formatting and for the --json and --stats flags to not have any effect. But that alternative makes dolphins cry 🐬 😢

lol true

@williebsweet curious on your thoughts here

**Comment by dlawin** [comment]
and @leoebfolsom @kylemcnair

**Comment by dbeatty10** [comment]
> we are targeting two very **_diff_** erent uses cases in these two features

😂 

The output format of regular `data-diff` felt familiar and comfortable due to its similarity with the `git diff` (and just `diff`) that I do regularly in the terminal. But when I used `data-diff --dbt`, I didn't really know what to do with the output.

At minimum, I'd like to be able to configure the output format via the `--json` and `--stats` flags  (along with a flag for the default format) when using `--dbt`.

But interested to hear everyone's thoughts on output formats that would be most useful during dbt model development!

In particular, how are the needs of Mary the Migrator and Dylan the dbt Developer similar and how are their needs different?  Is there particular diff output one persona needs that the other doesn't? Is there any overlap?

**Comment by dbeatty10** [comment]
@dlawin could we mark this as un-stale?

My feature proposal is to achieve parity across the output options (when using the `--dbt` option). I'll provide examples of all three below.

```shell
data-diff --dbt --dbt-profiles-dir .
```

<img width="484" alt="image" src="https://github.com/datafold/data-diff/assets/44704949/a3bce4c0-4b8b-42ed-8024-4bcd33f89f97">

```shell
data-diff --dbt --dbt-profiles-dir . --json
```

<img width="483" alt="image" src="https://github.com/datafold/data-diff/assets/44704949/c236307d-b9db-43e5-bad4-d5d678c5f8b5">

```shell
data-diff --dbt --dbt-profiles-dir . --stats
```

<img width="482" alt="image" src="https://github.com/datafold/data-diff/assets/44704949/588ac89b-0700-4bdb-9b59-4b310f194e32">

**Comment by kylemcnair** [comment]
> @dlawin could we mark this as un-stale?
> 
> My feature proposal is to achieve parity across the output options (when using the `--dbt` option). I'll provide examples of all three below.
> 
> ```shell
> data-diff --dbt --dbt-profiles-dir .
> ```
> 
> <img alt="image" width="484" src="https://user-images.githubusercontent.com/44704949/237383713-a3bce4c0-4b8b-42ed-8024-4bcd33f89f97.png">
> ```shell
> data-diff --dbt --dbt-profiles-dir . --json
> ```
> 
> <img alt="image" width="483" src="https://user-images.githubusercontent.com/44704949/237384002-c236307d-b9db-43e5-bad4-d5d678c5f8b5.png">
> ```shell
> data-diff --dbt --dbt-profiles-dir . --stats
> ```
> 
> <img alt="image" width="482" src="https://user-images.githubusercontent.com/44704949/237384110-588ac89b-0700-4bdb-9b59-4b310f194e32.png">

Hey @dbeatty10!
I removed the stale label - this seems like a great feature that we'd want to keep on the roadmap. We _just_ added the stale workflow in an attempt to better wrangle older issues, please pardon the noise as we get it dialed.

**Comment by dbeatty10** [comment]
No worries @kylemcnair -- stalebot is definitely handy to keep the backlog more manageable.

At the moment, the following is more of a link to interesting information rather than a feature request...

Another diff format to take a peek at is the one used by `daff`:
- http://paulfitz.github.io/daff-doc/spec.html

<img width="300" alt="image" src="https://github.com/datafold/data-diff/assets/44704949/14578295-610e-4e34-b395-5410d0cc4f7d">


I believe it originally came from the [coopy toolbox](http://share.find.coop/doc/coopy.html), and you can see it in action here:
- https://paulfitz.github.io/daff/

A relevant git repo is here:
- https://github.com/paulfitz/daff

**Comment by leoebfolsom** [comment]
@dbeatty10 I do really like the daff format, and believe it's a very good way to display row-level data diff info in CLI output, much better imo than the current "regular" (non-dbt) `data-diff` output. However, I echo what Kyle said above! We'll get there!

**Comment by dbeatty10** [comment]
@kylemcnair would you be open to either removing `stale` or adding `stale_immune` for this one?

**Comment by leoebfolsom** [comment]
Hi @dbeatty10!

I want to add that the traditional `git diff` format gets pretty unwieldy when there are many columns and rows, which is of course common when developing in dbt.

I know this from experience when trying to use 'main' `data-diff` to validate dbt model (comparing prod to dev), which I used to do in the before times, prior to the dbt integration. The output of `data-diff` was hard to read and overwhelming.

I believe the output of 'main' `data-diff` was built this way because of two assumptions that don't make sense for the dbt use case:

  - that the user is primarily interested in added/removed rows based on PKs, without the intent to compare the data in every column
  - that there will not be a huge number of differences, and that most rows will remain identical between the tables being compared (which would make sense when comparing source to target in a migration).

I support the general goal of feature parity across outputs for these different use cases (Mary and Dylan), but it doesn't seem trivial or obvious to me to identify what the _ideal_ common output structure would be. (As you mentioned above, there are distinctly different use cases.) 

I just want to make sure this is taken into account before something is designed and shipped. Perhaps the best answer is high-level parity, as in: the two use cases should have both machine-readable and human-readable summarized output; and machine-readable value-level output; but, the exact structure and implementation might differ for the two use cases. 

Finally, I'm curious if these recently shipped features influence your opinion on the direction and what should be prioritized:

- The VS Code extension (very much in beta / testing / pre-launch mode, but more than happy for you to try it out and give feedback 🙏 ): https://github.com/datafold/demo/blob/vscode-demo/VSCODE_INSTRUCTIONS.md
- The `--json` flag in the `--dbt` context

**Comment by sungchun12** [comment]
@dbeatty10 I'm planning to take on this feature for the next couple weeks. Let me know if any of your opinions changed on the above!

**Comment by sungchun12** [comment]
@kylemcnair would love your specific input since you last commented on this thread!

**Comment by dbeatty10** [comment]
> @dbeatty10 I'm planning to take on this feature for the next couple weeks. Let me know if any of your opinions changed on the above!

Nice, @sungchun12 😎

The above comments still reflect my primary thoughts:
1. When using the `--dbt` option, achieve parity across all the output options (`--json`, `--stats`, etc.)
1. If adding a new output option, then a `--daff` option would be interesting to look at

**Comment by sungchun12** [comment]
Alright, since this will be a pretty big change. I have a couple proposals in mind. 

**Scope:**
- This is specific to dbt use cases only and this PR is not expected to translate changes to xdb diffs
- Value-level diffs are Datafold cloud-specific only
- JSON outputs will store stats outputs, not value level diffs

**Comment by leoebfolsom** [comment]
I agree that the outputs (`--dbt` vs `--cloud` vs `--json` vs whatever else nifty future output) should have parity when equivalent information is available. This is table stakes.

**Comment by leoebfolsom** [comment]
I like the format Sung proposes ("Future diff outputs"). 

One nitpick is: I dislike how "changed rows" and "unchanged rows" are in columns specific to one vs the other side of the diff, because those are really meta statistics about the comparison of the two tables. 

In Cloud, we render that as "in the middle" which I think makes sense:
<img width="662" alt="Screenshot 2024-01-24 at 15 41 08" src="https://github.com/datafold/data-diff/assets/1799931/de4349bb-4a75-4c8f-8f30-8f00ae1c2090">

That said, I think it's fine as-is as an MVP.

**Comment by leoebfolsom** [comment]
I think sampling should be opt-in because I suspect it will be pretty hard to render sometimes, and I don't want people to have to run a diff, see that samples are rendered poorly, run it again, etc.

OTOH, if sampling renders nicely every time, even when there are 250 columns, then I would support opt-out.
