### ISSUE TITLE
Grouping By Arrays and Structs not supported in Bigquery

### ISSUE THREAD

**Issue by sowusu-ba** [datafold/data-diff#445]
**Describe the bug**
I tried data-diff for the first time and I got this error. 

```bash
Got error: 400 Grouping is not defined for arguments of type ARRAY<STRUCT<id STRING
```
My table has arrays and structs. The command I used is 

```bash
dbt run --select table_a && data-diff --dbt
```
I think what's happening is that the SQL generated by data-diff to compare the two tables is unaware that a field is an array of structs. I copied the SQL into the BigQuery console and I found the error here:

```sql
   CASE
      WHEN `tmp1`.`array_field` IS DISTINCT FROM `tmp2`.`array_field` THEN 1
    ELSE
    0
  END
    AS `is_diff_array_field`,
```

**Comment by dongchris** [comment]
+1, same error

**Comment by dongchris** [comment]
@leoebfolsom any update / ETA on this?

**Comment by i-zaykov** [comment]
+1 here

**Comment by leoebfolsom** [comment]
@i-zaykov @dongchris @brandon-segal I've reached out to the team to determine when we may be able to prioritize implementing this fix. 

Not to say any of you should take this on, but just as an FYI, we do accept community contributions if anyone felt inspired to spin up a PR. I mention this because I recognize it's been a while (longer than I originally anticipated), and I'm not positive when we'll be able to prioritize this update (but as I mentioned, I've inquired).

**Comment by leoebfolsom** [comment]
Hi all, just a note that a simplistic implementation was shipped in https://github.com/datafold/data-diff/pull/533 .

I'd be curious to hear if this meets the need for those of you watching the issue, and if it may be closed, or not. Please note some of the caveats mentioned in the description of the PR.

**Comment by dlawin** [comment]
I'm going to close this per the change in #533, feel free to reopen
