### ISSUE TITLE
Remove support for Python 3.7

### ISSUE THREAD

**Issue by dlawin** [datafold/data-diff#686]
**Is your feature request related to a problem? Please describe.**
Python 3.7 is past end of life, no need to continue support

**Comment by nolar** [comment]
An extra reason for dropping Python 3.7: MyPy (a type checker) [requires Python >= 3.8 since v1.5.0](https://github.com/python/mypy/commit/2edaf35ec1f91c139dfe1930b1b0d1e1cac59599#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) since 14.07.2023. We are going to add the type checking — it is better to have it with the newest tooling.
